apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "deployment.yml"
  - "ingress.yml"
  - "namespace.yml"
  - "service.yml"

images:
  - name: digitalphoenixx/masterquiz-frontend:latest
    newName: digitalphoenixx/masterquiz-frontend
    newTag: latest
